services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media          # user uploads
      - dbdata:/data              # sqlite DB persistence (/data/db.sqlite3)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5

volumes:
  media:
  dbdata:
