version: 2.1

orbs:
  accuknox-scan: accuknox/scan@1.0.0

workflows:
  accuknox:
    jobs:
      - printenv
      - accuknox-scan/sast:
          SOFT_FAIL: true



jobs:
  env-vars:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: env-vars
          command: |
            printenv

